### ISSUE TITLE
Streaming - also is there 1.0 yet?

### ISSUE THREAD

**Issue by timruffles** [tus/tus-resumable-upload-protocol#86] opened 2016-06-22 14:59 UTC
I'm confused. Streaming is in the 1.0 branch. There's a outstanding ticket for 1.0. Yet there's also 1.0 and apparently it's ready for use? http://tus.io/protocols/resumable-upload.html#status

Quite off-putting when considering whether to use this!

**Comment by Acconut** [comment] 2016-06-22 15:05
> Streaming is in the 1.0 branch.

Frankly, I cannot find a streaming functionality in the 1.0 branch (which has already been merged into master): https://github.com/tus/tus-resumable-upload-protocol/blob/1.0/protocol.md

> There's a outstanding ticket for 1.0.

#76 also contains topics which we wanted to address after the 1.0 launch but since we focused on more different aspects since then, they are still unresolved. Therefore the issue is open even though 1.0 has been released.

> Yet there's also 1.0 and apparently it's ready for use?

Yes, it is.

> Quite off-putting when considering whether to use this!

I apologize for this, I will try to cleanup the branches.

**Comment by timruffles** [comment] 2016-06-22 15:17
I spotted `Upload-Defer-Length` - that looks ok!

From the spec looks like I can fulfil my use case:

- start upload
- `PATCH` are NL JSON without `Upload-Length`
- finalise with either a real length or something made up

Nice work on the spec!

**Comment by Acconut** [comment] 2016-06-22 20:09
> Nice work on the spec!

Thank you. Glad to read that you were able to find what you were looking for :)
I'm going to close this, if you have another question or want to follow up on this topic feel free to reply or open a new issue.

**Closed by Acconut** 2016-06-22 20:09 UTC
